### ISSUE TITLE
server unstoppable

### ISSUE THREAD

**Issue by PAIREN1383** [theHamdiz/django-man#1]
سرور توی ویندوز ۱۱ متوقف نمیشه. موقع ساخت پروژه، فایل های دیگه که لازم هست ساخته نمیشه و من توانایی فعال یا غیر فعال کردن پروژه رو به صورت دستی با ترمینال ندارم چون پوشه‌ی "Scripts" وجود نداره.
The server does not stop in Windows 11. When building the project, other necessary files are not created, and I have no ability to activate or deactivate the project manually with the terminal because there is no "Scripts" folder.

**Comment by theHamdiz** [comment]
The extension stops the process it spawns, so if you started the server from another place such as the terminal, you won't be able to kill it using the extension.

Also, the functionality of this extension is to help execute django commands, nothing else.
